APPLICATION = plant_node
#include ../Makefile.tests_common

BOARD ?= samr21-xpro
RIOTBASE ?= $(CURDIR)/../../RIOT

FEATURES_REQUIRED = periph_adc

USEMODULE += vtimer

include $(RIOTBASE)/Makefile.include
